### ISSUE TITLE
Match Accept header rather than Content-Type

### ISSUE THREAD

**Issue by tdutrion** [phpro/api-problem-bundle#10]
The type of expected answer should be used rather than the type of the request body content type to define whether to use the library from what I understand.

For instance, say you have a get request: there is no need for a Content-Type, and I believe a Get request should never have a body, hence no content-type.

**Comment by veewee** [comment]
True. We mostly use the route content type - but it makes sense to add an accept check as well.
Feel free to send us a PR.

**Comment by tdutrion** [comment]
I'm not sure what to do exactly:

- should I just add the case when the header exists (done in the PR)
- should we allow people to choose which methods trigger the bundle (with a configuration Accept = true, Content-Type = true, RequestType = true)
- something else...

**Comment by veewee** [comment]
Making it configurable seems like a step too far for new. Let's continue the discussion in the PR!
