### ISSUE TITLE
Compile error with symfony 6.0

### ISSUE THREAD

**Issue by AnneSmids** [phpro/api-problem-bundle#16]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.4.0

#### Summary

Updating to symfony 6.0 gives a compile error in ApiProblemHttpException. The return types are missing in the code.

**Comment by veewee** [comment]
Thanks for reporting!
Care to create a PR for this?

**Comment by AnneSmids** [comment]
> Thanks for reporting! Care to create a PR for this?

Yes I will try it.

**Comment by veewee** [comment]
Thanks
