### ISSUE TITLE
Add symfony Validator Transformer

### ISSUE THREAD

**Issue by leroy0211** [phpro/api-problem-bundle#5]
Symfony Validator component has a built in feature to normalize a `ConstraintViolationListInterface` to an RFC7807 output. However, you need to do this by returning this yourself like so: 

```php
# IndexController.php

public function index(ValidatorInterface $validator) 
{
     $errors = $validator->validate(...);
     return $this->json($errors, 400);
}

```

It would be much nicer to throw an exception, because in the above example, it is very easy to mis the response status. And with an exception it doesn't. 

Maybe something like: 

```php
throw new ApiValidationException($errors);
```

Or does this package already has a solution for it?

**Comment by veewee** [comment]
Hello @leroy0211,

This one is already built-in in the main package:
https://github.com/phpro/api-problem#validationapiproblem

```
new ValidationApiProblem($errors);
```

You can wrap and throw an `ExceptionApiProblem` or create your own `ValidationFailedException` and add a transformer for that one.
